In [20]:
import numpy as np

In [21]:
x=np.array([1,2,3,4,5,6,7])

In [22]:
x[4]

5

In [23]:
x[5]

6

In [24]:
x[x>5]

array([6, 7])

In [25]:
x[[1,2,3]]

array([2, 3, 4])

In [26]:
x=np.random.randn(10,10)

In [27]:
x

array([[ 4.70591315e-01,  2.17590258e-01,  3.78394867e-01,
         1.43792781e+00, -1.88490962e+00,  8.48415830e-01,
        -1.47510881e-01,  1.27203468e+00, -4.86406884e-01,
         2.96442022e-01],
       [-2.12120550e-01, -7.44285778e-01,  5.24344936e-01,
        -3.76014273e-01,  6.19059074e-01, -8.14853034e-01,
        -4.96341435e-01,  1.03270178e+00, -4.86156327e-01,
        -1.18034556e+00],
       [-5.69167819e-01, -1.77316143e+00, -5.19819769e-01,
         8.42964453e-01, -1.01950974e+00, -3.07655649e-01,
         3.56035238e-01,  1.99088643e+00, -2.93219892e-01,
        -1.69522848e-02],
       [-2.02331257e-03, -8.48623295e-01, -4.38246028e-01,
         5.05249522e-02,  2.29461264e+00, -4.57219592e-01,
         2.26115070e+00, -1.21194825e+00, -1.28122308e+00,
        -1.06145287e+00],
       [-4.76932158e-01, -5.47165498e-01,  9.03252498e-01,
        -1.45591814e-01, -6.78261524e-01, -6.62452412e-01,
        -5.14761644e-01,  1.04054532e+00,  4.55236098e-01,
        -4.

In [28]:
x[0][4]

-1.8849096211663299

In [29]:
x[4][4]

-0.6782615239412828

In [30]:
x[0][3]

1.4379278121262158

In [31]:
x[1][3]

-0.376014273072432

In [32]:
x[1:10:2]

array([[-2.12120550e-01, -7.44285778e-01,  5.24344936e-01,
        -3.76014273e-01,  6.19059074e-01, -8.14853034e-01,
        -4.96341435e-01,  1.03270178e+00, -4.86156327e-01,
        -1.18034556e+00],
       [-2.02331257e-03, -8.48623295e-01, -4.38246028e-01,
         5.05249522e-02,  2.29461264e+00, -4.57219592e-01,
         2.26115070e+00, -1.21194825e+00, -1.28122308e+00,
        -1.06145287e+00],
       [-2.23950348e+00,  5.11380585e-01,  8.55759904e-01,
         1.48246822e+00,  6.24662905e-01,  2.28527006e+00,
        -1.07976274e+00, -2.29690050e+00,  6.58111516e-01,
        -7.42077182e-01],
       [ 8.65405109e-01, -4.39848797e-01,  2.31929681e-01,
        -6.12146069e-01,  8.54267690e-01,  7.58946829e-01,
         4.82893885e-01,  1.38666004e+00, -1.92204504e+00,
         1.62456290e+00],
       [-7.10444347e-01,  1.47143569e+00,  2.54217055e+00,
        -2.32678149e-01, -1.90897055e+00,  1.83853738e-01,
         2.37205671e+00, -3.26266597e-01, -1.06359719e-02,
         1.

In [33]:
x[::,0:4]

array([[ 4.70591315e-01,  2.17590258e-01,  3.78394867e-01,
         1.43792781e+00],
       [-2.12120550e-01, -7.44285778e-01,  5.24344936e-01,
        -3.76014273e-01],
       [-5.69167819e-01, -1.77316143e+00, -5.19819769e-01,
         8.42964453e-01],
       [-2.02331257e-03, -8.48623295e-01, -4.38246028e-01,
         5.05249522e-02],
       [-4.76932158e-01, -5.47165498e-01,  9.03252498e-01,
        -1.45591814e-01],
       [-2.23950348e+00,  5.11380585e-01,  8.55759904e-01,
         1.48246822e+00],
       [-5.41325318e-01, -1.55906401e+00,  6.66225100e-01,
        -1.75048830e+00],
       [ 8.65405109e-01, -4.39848797e-01,  2.31929681e-01,
        -6.12146069e-01],
       [ 6.98619016e-01, -1.40816569e-02,  1.31173985e+00,
        -1.23635526e+00],
       [-7.10444347e-01,  1.47143569e+00,  2.54217055e+00,
        -2.32678149e-01]])

In [34]:
x=np.ones([5,5])

In [35]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
x[1:-1,1:-1]=0

In [37]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# function

In [38]:
x=([4,5,2,7,8])

In [39]:
y=([4,6,8,0,3])

In [40]:
np.maximum(y,x)

array([4, 6, 8, 7, 8])

# where

In [41]:
salary=np.array([0,-1,10000,20000])

In [42]:
np.where(salary<=0,25000,salary)

array([25000, 25000, 10000, 20000])

In [43]:
np.where(salary<=0,"not ok","ok")

array(['not ok', 'not ok', 'ok', 'ok'], dtype='<U6')

# mathematical and statistical methods

In [44]:
import numpy as np

In [45]:
x=np.array([8,5,6,7,2,4])

In [46]:
x.mean()

5.333333333333333

In [47]:
x.cumsum() #yy sum ase nekalta hai k 1,2 ko melai ga pher 1,2,3 ko pher 1,2,3,4 ko ........

array([ 8, 13, 19, 26, 28, 32], dtype=int32)

In [48]:
x.cumprod()#yy multiple kare ga 

array([    8,    40,   240,  1680,  3360, 13440], dtype=int32)

# method for boolen arrays

In [49]:
y=x>6#matlab 6 se bhare num ko true kare ga

In [50]:
y

array([ True, False, False,  True, False, False])

In [51]:
y.sum()#yy 6 se bhare num ka sum nekal k de ga

2

In [52]:
y.any()#yy batai g k 6 se chote num hain ya ni

True

In [53]:
y.all()#yy batai ga k sab num chote hi ya ni


False

In [54]:
x.sort()#num ko tarteeb se le aai ga

In [55]:
x

array([2, 4, 5, 6, 7, 8])

In [56]:
np.unique(x)

array([2, 4, 5, 6, 7, 8])

# file input output

In [59]:
import numpy as ny

In [60]:
x=[2,4,6,8]

In [61]:
y=[1,3,5,7]

In [62]:
ny.save("bilal",x)

In [64]:
z=ny.load("bilal.npy")

In [65]:
z

array([2, 4, 6, 8])

In [66]:
ny.savez("testxy",x,y)

In [67]:
xy=ny.load("testxy.npz")

In [68]:
xy

In [70]:
loadxy[x]

NameError: name 'loadxy' is not defined

# liner algebra function

In [71]:
import numpy as np

In [74]:
x=np.random.randn(3,2)

In [77]:
y=np.random.randn(2,3)

In [78]:
x.dot(y)

array([[-1.36486922,  0.44019975, -1.7566452 ],
       [-0.49521805, -0.38823891, -0.60683733],
       [ 0.80704576, -0.08225108,  1.02878305]])

In [79]:
x.transpose()

array([[-0.14746595, -1.69364355,  0.62009897],
       [-1.10600445, -0.44745624,  0.66897812]])

In [80]:
x.trace()

-0.5949221977661469

# rendom number

In [85]:
np.random.seed(7)

In [86]:
np.random.normal(size=(3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [87]:
np.random.uniform(size=(3,3))

array([[0.38094113, 0.06593635, 0.2881456 ],
       [0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892]])