In [2]:
import numpy as np

In [3]:
l=range(1000000)
print(l)

range(0, 1000000)


In [4]:
d=np.arange(1000000)
print(d)

[     0      1      2 ... 999997 999998 999999]


In [5]:
%time for i in range(1,10): r=[x*2 for x in l]

Wall time: 1.84 s


In [6]:
%time for i in range(1,10): r=d*2

Wall time: 59.9 ms


In [7]:
for i in range(10)

SyntaxError: invalid syntax (<ipython-input-7-9bf3d452bb2a>, line 1)

In [ ]:
x=np.array([1,2,3,4,5,6,7])

In [ ]:
x[4]

In [ ]:
x[5]

In [ ]:
x[x>5]

In [ ]:
x[[1,2,3]]

In [ ]:
x=np.random.randn(10,10)

In [ ]:
x

In [ ]:
x[0][4]

In [ ]:
x[4][4]

In [ ]:
x[0][3]

In [ ]:
x[1][3]

In [ ]:
x[1:10:2]#yy bata rehe hain k 1 se le kar 10 tak row mein se har 2sri row print ki jai or columns sara aai ge auto par ya ham is k bad :: bhe laga sakte hain

In [ ]:
x[::,0:4]#yahan par sab ro or 0 se 4 tak columns chai hain

In [ ]:
x=np.ones([5,5])

In [ ]:
x

In [ ]:
x[1:-1,1:-1]=0#

In [ ]:
x

# function

In [8]:
x=([4,5,2,7,8])

In [9]:
y=([4,6,8,0,3])

In [10]:
np.maximum(y,x)

array([4, 6, 8, 7, 8])

# where

In [11]:
salary=np.array([0,-1,10000,20000])

In [12]:
np.where(salary<=0,25000,salary)

array([25000, 25000, 10000, 20000])

In [13]:
np.where(salary<=0,"not ok","ok")

array(['not ok', 'not ok', 'ok', 'ok'], dtype='<U6')

# mathematical and statistical methods

In [14]:
import numpy as np

In [15]:
x=np.array([8,5,6,7,2,4])

In [16]:
x.mean()

5.333333333333333

In [17]:
x.cumsum() #yy sum ase nekalta hai k 1,2 ko melai ga pher 1,2,3 ko pher 1,2,3,4 ko ........

array([ 8, 13, 19, 26, 28, 32], dtype=int32)

In [18]:
x.cumprod()#yy multiple kare ga 

array([    8,    40,   240,  1680,  3360, 13440], dtype=int32)

# method for boolen arrays

In [19]:
y=x>6#matlab 6 se bhare num ko true kare ga

In [20]:
y

array([ True, False, False,  True, False, False])

In [21]:
y.sum()#yy 6 se bhare num ka sum nekal k de ga

2

In [22]:
y.any()#yy batai g k 6 se chote num hain ya ni

True

In [23]:
y.all()#yy batai ga k sab num chote hi ya ni


False

In [24]:
x.sort()#num ko tarteeb se le aai ga

In [25]:
x

array([2, 4, 5, 6, 7, 8])

In [26]:
np.unique(x)

array([2, 4, 5, 6, 7, 8])

# file input output

In [27]:
import numpy as ny

In [28]:
x=[2,4,6,8]

In [29]:
y=[1,3,5,7]

In [30]:
ny.save("bilal",x)

In [31]:
z=ny.load("bilal.npy")

In [39]:
z

array([2, 4, 6, 8])

In [46]:
ny.savez("testxy",x=x,y=y)

In [47]:
loadxy=ny.load("testxy.npz")

In [48]:
loadxy

In [49]:
loadxy["x"]

array([2, 4, 6, 8])

In [50]:
loadxy["y"]

array([1, 3, 5, 7])

In [55]:
loadxy["x"]

array([2, 4, 6, 8])

# liner algebra function

In [56]:
import numpy as np

In [57]:
x=np.random.randn(3,2)

In [58]:
y=np.random.randn(2,3)

In [59]:
x.dot(y)

array([[ 1.51693069,  3.01441841, -0.54880305],
       [ 1.98626305,  4.3149877 , -0.83701578],
       [ 1.22442677,  3.02950882, -0.63491466]])

In [60]:
x.transpose()

array([[-1.43537315, -2.18233603, -1.64949768],
       [-0.19441531,  0.23510195,  0.63676004]])

In [61]:
x.trace()

-1.2002712005880793

# rendom number

In [65]:
np.random.seed(7)

In [66]:
np.random.normal(size=(3,3))

array([[ 1.69052570e+00, -4.65937371e-01,  3.28201637e-02],
       [ 4.07516283e-01, -7.88923029e-01,  2.06557291e-03],
       [-8.90385858e-04, -1.75472431e+00,  1.01765801e+00]])

In [67]:
np.random.uniform(size=(3,3))

array([[0.38094113, 0.06593635, 0.2881456 ],
       [0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892]])