In [1]:
import numpy as np

In [4]:
x=np.zeros((4,4))

In [5]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((5,5,))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.empty((7,7))

array([[1.44040263e-311, 1.44040050e-311, 2.60866661e-321,
        1.97626258e-323, 4.42682819e-321, 2.03060980e-321,
        2.94463125e-321],
       [6.47522026e+170, 4.20943930e-321, 2.28251382e+232,
        3.95252517e-321, 4.27255552e+180, 4.74303020e-321,
        5.83439358e+252],
       [5.45448473e-321, 4.37214672e+156, 5.35567160e-321,
        4.71353286e+257, 2.60866661e-321, 2.58413295e+161,
        2.62842924e-321],
       [6.24379810e-119, 3.81418679e-321, 1.36456517e+161,
        2.60866661e-321, 4.71341830e+257, 2.44084997e-154,
        6.08709837e+247],
       [1.61674072e+184, 2.63433603e-085, 6.75854449e+199,
        2.35288410e+251, 3.99193922e+252, 1.08785657e+155,
        2.20892690e+161],
       [5.55183541e-048, 1.72053723e+243, 1.81596890e-152,
        1.69375774e+190, 2.97399120e+222, 1.11493509e+277,
        6.77023426e+223],
       [9.69279043e-072, 8.92892213e+271, 1.06112832e-153,
        2.32160044e-152, 2.73461243e+161, 2.43566010e-154,
        1.04019395

In [14]:
l=[1,4,5,7]

In [15]:
np.array(l)

array([1, 4, 5, 7])

In [12]:
x=np.arange(1,100,10)

In [13]:
x.shape

(10,)

In [14]:
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [16]:
x=np.zeros((10,10))

In [17]:
x.shape

(10, 10)

In [18]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
y=x.reshape((2,2,5,5))

In [24]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [25]:
y.dtype

dtype('float64')

In [26]:
y.ndim

4

In [29]:
a=np.random.randn((10))

In [30]:
b=np.random.randn((10))

In [31]:
a

array([ 1.90617084,  1.6187676 ,  0.91378116,  0.47731718,  0.93825787,
        0.52310042, -1.31339607, -0.79495823, -1.08522323, -0.41961623])

In [32]:
b

array([ 1.30277723, -0.9377809 ,  1.65404177, -1.33796885,  1.20499997,
       -1.63711169,  0.64754351, -0.42949079,  0.83496274,  0.79269504])

In [33]:
a+b

array([ 3.20894807,  0.6809867 ,  2.56782293, -0.86065167,  2.14325784,
       -1.11401127, -0.66585256, -1.22444901, -0.2502605 ,  0.37307881])

In [34]:
 1/a

array([ 0.52461195,  0.6177539 ,  1.09435393,  2.09504295,  1.06580508,
        1.91167881, -0.76138495, -1.25792773, -0.9214694 , -2.38312997])

In [35]:
2/a

array([ 1.0492239 ,  1.2355078 ,  2.18870786,  4.19008589,  2.13161016,
        3.82335763, -1.5227699 , -2.51585546, -1.8429388 , -4.76625993])

In [36]:
a>0

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [37]:
a[a>0]

array([1.90617084, 1.6187676 , 0.91378116, 0.47731718, 0.93825787,
       0.52310042])

# reshape row major order and column mejor order

In [19]:
import numpy as np

In [20]:
x=np.random.randn(4,5)

In [21]:
x.reshape(2,2,5)

array([[[-1.2131114 , -1.91444239,  0.00291171, -0.06303364,
         -1.43425788],
        [-1.36388873,  1.13493813, -0.47768655,  1.56807131,
         -0.34718842]],

       [[ 1.24072835, -0.73031418,  0.18203721,  1.21306836,
          0.20498752],
        [-0.42886874,  0.08610941, -0.98008355, -1.05853841,
         -2.23546719]]])

In [25]:
x.reshape((2,2,5),order="f")

array([[[-1.2131114 , -1.91444239,  0.00291171, -0.06303364,
         -1.43425788],
        [ 1.24072835, -0.73031418,  0.18203721,  1.21306836,
          0.20498752]],

       [[-1.36388873,  1.13493813, -0.47768655,  1.56807131,
         -0.34718842],
        [-0.42886874,  0.08610941, -0.98008355, -1.05853841,
         -2.23546719]]])

In [26]:
x.reshape(2,2,-1)

array([[[-1.2131114 , -1.91444239,  0.00291171, -0.06303364,
         -1.43425788],
        [-1.36388873,  1.13493813, -0.47768655,  1.56807131,
         -0.34718842]],

       [[ 1.24072835, -0.73031418,  0.18203721,  1.21306836,
          0.20498752],
        [-0.42886874,  0.08610941, -0.98008355, -1.05853841,
         -2.23546719]]])

In [28]:
x.ravel()

array([-1.2131114 , -1.91444239,  0.00291171, -0.06303364, -1.43425788,
       -1.36388873,  1.13493813, -0.47768655,  1.56807131, -0.34718842,
        1.24072835, -0.73031418,  0.18203721,  1.21306836,  0.20498752,
       -0.42886874,  0.08610941, -0.98008355, -1.05853841, -2.23546719])

# concatenate_function

In [29]:
import  numpy as np

In [31]:
x=[[1,3,5,6],[7,5,4,2]]

In [32]:
y=[[3,5,7,8],[4,6,9,2]]

In [33]:
arr1=np.array(x)

In [34]:
arr2=np.array(y)

In [35]:
np.concatenate((arr1,arr2),axis=0)

array([[1, 3, 5, 6],
       [7, 5, 4, 2],
       [3, 5, 7, 8],
       [4, 6, 9, 2]])

In [37]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 3, 5, 6, 3, 5, 7, 8],
       [7, 5, 4, 2, 4, 6, 9, 2]])

In [47]:
np.vstack((arr1,arr2))

array([[1, 3, 5, 6],
       [7, 5, 4, 2],
       [3, 5, 7, 8],
       [4, 6, 9, 2]])

In [48]:
np.hstack((arr1,arr2))

array([[1, 3, 5, 6, 3, 5, 7, 8],
       [7, 5, 4, 2, 4, 6, 9, 2]])

In [38]:
r=[[1,2,3,4],[6,7,8]]

In [40]:
t=[[6,7,8],[4,5,6,7]]

In [41]:
arr3=np.array(r)

In [42]:
arr4=np.array(t)

In [43]:
np.concatenate((arr3,arr4),axis=0)

array([list([1, 2, 3, 4]), list([6, 7, 8]), list([6, 7, 8]),
       list([4, 5, 6, 7])], dtype=object)

In [45]:
np.concatenate((arr3,arr4),axis=1)#yy galat ho jai ga q k yy order k khelaf hai

AxisError: axis 1 is out of bounds for array of dimension 1

# split

In [49]:
import numpy as np

In [50]:
x=[1,2,3,4,5,6,78,9,0]

In [51]:
d=np.array(x)

In [52]:
np.split(d,(4,6))

[array([1, 2, 3, 4]), array([5, 6]), array([78,  9,  0])]

In [53]:
y=[1,2,3,4,5,6,7,8,9,],[11,22,33,44,55,66,77,88,99,]

In [54]:
f=np.array(y)

In [61]:
np.split(f,(2,4),axis=0)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [11, 22, 33, 44, 55, 66, 77, 88, 99]]),
 array([], shape=(0, 9), dtype=int32),
 array([], shape=(0, 9), dtype=int32)]

# tile and repeat

In [63]:
import numpy as np

In [64]:
x=[1,2,3]

In [65]:
e=np.array(x)

In [67]:
np.repeat(e,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [68]:
np.tile(e,4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])