In [1]:
import numpy as np

In [2]:
x=np.zeros((4,4))

In [3]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((5,5,))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.empty((7,7))

array([[1.10104841e-311, 1.10104942e-311, 4.64421707e-321,
        1.97626258e-323, 5.13828272e-321, 1.09919382e-311,
        5.15804534e-321],
       [1.09919382e-311, 5.21733322e-321, 1.09919382e-311,
        5.27662110e-321, 1.09919382e-311, 5.35567160e-321,
        1.09919382e-311],
       [4.64421707e-321, 1.09919382e-311, 4.62445445e-321,
        1.09919382e-311, 2.78653024e-321, 1.09919382e-311,
        6.04736351e-321],
       [1.09919382e-311, 6.08688876e-321, 1.09919382e-311,
        4.64421707e-321, 1.09919382e-311, 1.10105865e-311,
        1.10105863e-311],
       [1.10105863e-311, 1.10105863e-311, 1.10105863e-311,
        1.10105863e-311, 1.10105866e-311, 1.10105866e-311,
        1.10105866e-311],
       [1.10105866e-311, 1.10105866e-311, 1.10105866e-311,
        1.10105866e-311, 1.10105866e-311, 1.10105866e-311,
        1.10105866e-311],
       [1.10105866e-311, 1.10105873e-311, 1.10105873e-311,
        1.10105873e-311, 1.10105873e-311, 1.10105873e-311,
        1.10105873

In [6]:
l=[1,4,5,7]

In [7]:
np.array(l)

array([1, 4, 5, 7])

In [8]:
x=np.arange(1,100,10)

In [9]:
x.shape

(10,)

In [10]:
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [11]:
x=np.zeros((10,10))

In [12]:
x.shape

(10, 10)

In [13]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
y=x.reshape((5,5,2,2))#5*5=25 arry bane gi 2*2 ki ak arry ho gi first 2 batai gy k kitni arry bane gi or last 2 ya ak k kitne ki bane gi

In [15]:
y

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0.,

In [16]:
y.shape

(5, 5, 2, 2)

In [17]:
y.dtype

dtype('float64')

In [18]:
y.ndim

4

In [19]:
a=np.random.randn((10))

In [20]:
b=np.random.randn((10))

In [21]:
a

array([-1.27411094, -0.49077448,  0.6771133 , -0.72754525,  1.1481483 ,
        0.11212896, -0.90308931, -0.84892316,  0.42086807,  1.39610877])

In [22]:
b

array([-0.718781  , -0.71935252, -0.04447538,  0.67982328, -0.03692875,
       -0.87155615, -0.59466094, -0.40213071, -0.02490101,  0.57481595])

In [23]:
a+b

array([-1.99289194, -1.210127  ,  0.63263792, -0.04772196,  1.11121955,
       -0.75942719, -1.49775024, -1.25105386,  0.39596706,  1.97092472])

In [24]:
 1/a

array([-0.78486101, -2.03759575,  1.47685772, -1.37448496,  0.87096763,
        8.91830283, -1.1073102 , -1.17796292,  2.37604148,  0.71627657])

In [25]:
2/a

array([-1.56972202, -4.0751915 ,  2.95371543, -2.74896993,  1.74193525,
       17.83660567, -2.2146204 , -2.35592584,  4.75208296,  1.43255314])

In [26]:
a>0

array([False, False,  True, False,  True,  True, False, False,  True,
        True])

In [27]:
a[a>0]

array([0.6771133 , 1.1481483 , 0.11212896, 0.42086807, 1.39610877])

# reshape row major order and column mejor order

In [28]:
import numpy as np

In [29]:
x=np.random.randn(4,5)

In [30]:
x.reshape(2,2,5)

array([[[-1.08036126, -1.08947926, -1.22558461, -0.08535568,
         -1.34791811],
        [ 0.84420249, -1.38369971,  1.72875386,  0.45520067,
         -0.27688222]],

       [[-0.96540718,  0.53689616,  0.8200032 , -0.40742519,
         -0.94569885],
        [-0.30656562,  0.65582892, -1.0570293 ,  0.86698785,
         -0.73548582]]])

In [31]:
x.reshape((2,2,5),order="f")

array([[[-1.08036126, -1.08947926, -1.22558461, -0.08535568,
         -1.34791811],
        [-0.96540718,  0.53689616,  0.8200032 , -0.40742519,
         -0.94569885]],

       [[ 0.84420249, -1.38369971,  1.72875386,  0.45520067,
         -0.27688222],
        [-0.30656562,  0.65582892, -1.0570293 ,  0.86698785,
         -0.73548582]]])

In [32]:
x.reshape(2,2,-1)

array([[[-1.08036126, -1.08947926, -1.22558461, -0.08535568,
         -1.34791811],
        [ 0.84420249, -1.38369971,  1.72875386,  0.45520067,
         -0.27688222]],

       [[-0.96540718,  0.53689616,  0.8200032 , -0.40742519,
         -0.94569885],
        [-0.30656562,  0.65582892, -1.0570293 ,  0.86698785,
         -0.73548582]]])

In [33]:
x.ravel()

array([-1.08036126, -1.08947926, -1.22558461, -0.08535568, -1.34791811,
        0.84420249, -1.38369971,  1.72875386,  0.45520067, -0.27688222,
       -0.96540718,  0.53689616,  0.8200032 , -0.40742519, -0.94569885,
       -0.30656562,  0.65582892, -1.0570293 ,  0.86698785, -0.73548582])

# concatenate_function

In [34]:
import  numpy as np

In [35]:
x=[[1,3,5,6],[7,5,4,2]]

In [36]:
y=[[3,5,7,8],[4,6,9,2]]

In [37]:
arr1=np.array(x)

In [38]:
arr2=np.array(y)

In [39]:
np.concatenate((arr1,arr2),axis=0)

array([[1, 3, 5, 6],
       [7, 5, 4, 2],
       [3, 5, 7, 8],
       [4, 6, 9, 2]])

In [40]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 3, 5, 6, 3, 5, 7, 8],
       [7, 5, 4, 2, 4, 6, 9, 2]])

In [41]:
np.vstack((arr1,arr2))

array([[1, 3, 5, 6],
       [7, 5, 4, 2],
       [3, 5, 7, 8],
       [4, 6, 9, 2]])

In [42]:
np.hstack((arr1,arr2))

array([[1, 3, 5, 6, 3, 5, 7, 8],
       [7, 5, 4, 2, 4, 6, 9, 2]])

In [43]:
r=[[1,2,3,4],[6,7,8]]

In [44]:
t=[[6,7,8],[4,5,6,7]]

In [45]:
arr3=np.array(r)

In [46]:
arr4=np.array(t)

In [47]:
np.concatenate((arr3,arr4),axis=0)

array([list([1, 2, 3, 4]), list([6, 7, 8]), list([6, 7, 8]),
       list([4, 5, 6, 7])], dtype=object)

In [48]:
np.concatenate((arr3,arr4),axis=1)#yy galat ho jai ga q k yy order k khelaf hai

AxisError: axis 1 is out of bounds for array of dimension 1

# split

In [49]:
import numpy as np

In [50]:
x=[1,2,3,4,5,6,78,9,0]

In [51]:
d=np.array(x)

In [52]:
np.split(d,(4,6))

[array([1, 2, 3, 4]), array([5, 6]), array([78,  9,  0])]

In [53]:
y=[1,2,3,4,5,6,7,8,9,],[11,22,33,44,55,66,77,88,99,]

In [54]:
f=np.array(y)

In [55]:
np.split(f,(2,4),axis=0)

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [11, 22, 33, 44, 55, 66, 77, 88, 99]]),
 array([], shape=(0, 9), dtype=int32),
 array([], shape=(0, 9), dtype=int32)]

# tile and repeat

In [56]:
import numpy as np

In [57]:
x=[1,2,3]

In [58]:
e=np.array(x)

In [59]:
np.repeat(e,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [60]:
np.tile(e,4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# practice

In [61]:
import numpy as np

In [62]:
g=np.random.randn(10,5)

In [63]:
g

array([[ 0.33485305,  0.97784229,  0.96064443, -1.32116827, -1.26926551],
       [-0.25240856, -1.11657055,  0.08046556,  0.55693505,  1.77284998],
       [-0.79868102, -0.58359106,  1.13088113,  0.10205668, -0.352537  ],
       [-0.53395541,  0.19788259,  0.59033867,  0.30713696, -0.64840401],
       [-0.28887267, -0.65207306, -0.30759238,  0.17129185, -0.70905071],
       [ 0.04127244, -0.93145425,  0.1183111 ,  1.03865247,  0.8803211 ],
       [ 1.07283277,  1.55321233,  0.100649  ,  0.95073558, -1.31967208],
       [-0.69837539, -0.60776298,  0.92655803, -1.02488363, -0.2741254 ],
       [-0.74127454,  2.12148538, -0.29623355,  0.47643227, -0.04150885],
       [ 1.91081743, -0.12309263, -0.12677256, -1.85323336,  0.0588884 ]])