In [9]:
#must be import panda
import pandas as pd
obj=pd.Series([4,5,6,7,8])
print(obj)

0    4
1    5
2    6
3    7
4    8
dtype: int64


In [10]:
import pandas as pd

In [11]:
dd=pd.Series([1,2,3,4,5,8])

In [12]:
dd

0    1
1    2
2    3
3    4
4    5
5    8
dtype: int64

In [13]:
print(dd)

0    1
1    2
2    3
3    4
4    5
5    8
dtype: int64


In [14]:
obj

0    4
1    5
2    6
3    7
4    8
dtype: int64

# pandas Sereis has two things in one object
1) values
2)index

In [15]:
sales=pd.Series([100,200,333,444])
print(sales.values)

[100 200 333 444]


In [16]:
sales=pd.Series([100,200,333,444])
print(sales.values)
print(sales.index)

[100 200 333 444]
RangeIndex(start=0, stop=4, step=1)


In [17]:
sales=pd.Series([100,200,333,444],index=["a","b","c","d"])
print(sales.values)
print(sales.index)

[100 200 333 444]
Index(['a', 'b', 'c', 'd'], dtype='object')


In [18]:
print(sales)

a    100
b    200
c    333
d    444
dtype: int64


In [19]:
sales1=pd.Series([100,200,333,444],index=["a","b","c","d"],name="4 month sales")

In [20]:
sales1

a    100
b    200
c    333
d    444
Name: 4 month sales, dtype: int64

# creat a pandas Series to store a canteen data to hold values of how many sanhwithes are sold each day (a week)

In [21]:
sw=pd.Series([0,10,22,33,44,55,66],index=["sun","m0n","tue","wen","thu","fri","sat"])
print(sw)

sun     0
m0n    10
tue    22
wen    33
thu    44
fri    55
sat    66
dtype: int64


In [22]:
#call value by position

In [23]:
print(sw[3])

33


In [24]:
#call value by index

In [25]:
print(sw["wen"])

33


In [26]:
#multipul value ko call karne k lea array notation lagana hota hai

In [27]:
print(sw[[2,5]])

tue    22
fri    55
dtype: int64


In [28]:
print(sw[["m0n","fri"]])

m0n    10
fri    55
dtype: int64


In [29]:
#conditional call

In [30]:
print(sw>20)

sun    False
m0n    False
tue     True
wen     True
thu     True
fri     True
sat     True
dtype: bool


In [31]:
print(sw[sw>20])

tue    22
wen    33
thu    44
fri    55
sat    66
dtype: int64


In [32]:
print(sw[sw<44])

sun     0
m0n    10
tue    22
wen    33
dtype: int64


In [33]:
# * , /

In [34]:
sw * 2 #sw * 2 karne se value us time k lea change ho jai gi par sw ki orignal value par farq ni phare ga.or print sw karane par sw ki orignal value aai gi
print(sw)

sun     0
m0n    10
tue    22
wen    33
thu    44
fri    55
sat    66
dtype: int64


In [35]:
sw * 2 #sw * 2 karne se value us time k lea change ho jai gi par sw ki orignal value par farq ni phare ga.

sun      0
m0n     20
tue     44
wen     66
thu     88
fri    110
sat    132
dtype: int64

In [36]:
sw

sun     0
m0n    10
tue    22
wen    33
thu    44
fri    55
sat    66
dtype: int64

In [37]:
#value change karne k lea 

In [38]:
sw = sw * 2

In [39]:
print (sw)

sun      0
m0n     20
tue     44
wen     66
thu     88
fri    110
sat    132
dtype: int64


In [40]:
sw = sw / 2

In [41]:
print(sw)

sun     0.0
m0n    10.0
tue    22.0
wen    33.0
thu    44.0
fri    55.0
sat    66.0
dtype: float64


In [42]:
sw

sun     0.0
m0n    10.0
tue    22.0
wen    33.0
thu    44.0
fri    55.0
sat    66.0
dtype: float64

In [43]:
"55.0" in sw

False

In [44]:
"sat" in sw

True

In [45]:
#numpy ky data ko panda mein add karne k lea

In [111]:
import numpy as np
ar=np.array([1,2,3,4,5,6])
print(ar)

[1 2 3 4 5 6]


In [109]:
import numpy as np
ar=np.array([1,2,3,4,5,6])
ind=np.array(["a","b","c","d","e","f"])

obj2=pd.Series(ar, index=ind)
print(obj2)

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int32


In [47]:
#dictionary ky data ko panda mein add karne k lea

In [48]:
sdata={"bilal":4500000,"haroon":300000000,"adnan":345555555,"junaid":50000000}
tax_pay=pd.Series(sdata)
print(tax_pay)

bilal       4500000
haroon    300000000
adnan     345555555
junaid     50000000
dtype: int64


In [49]:
print(tax_pay.index)

Index(['bilal', 'haroon', 'adnan', 'junaid'], dtype='object')


In [50]:
sdata={"bilal":4500000,"haroon":300000000,"adnan":345555555,"junaid":50000000}
tax_pay=pd.Series(sdata,index=["bilal","haroon","adnan","junaid"])
print(tax_pay)

bilal       4500000
haroon    300000000
adnan     345555555
junaid     50000000
dtype: int64


In [112]:
sdata={"bilal":4500000,"haroon":300000000,"adnan":345555555,"junaid":50000000}
tax_pay=pd.Series(sdata)
print(tax_pay)

bilal       4500000
haroon    300000000
adnan     345555555
junaid     50000000
dtype: int64


In [51]:
#agar index change kare ge to value bhe change ho jai ge jase bilal ki jaga horon or haroon ki jaga bilal.
sdata={"bilal":4500000,"haroon":300000000,"adnan":345555555,"junaid":50000000}
tax_pay=pd.Series(sdata,index=["haroon","bilal","adnan","junaid"])
print(tax_pay)

haroon    300000000
bilal       4500000
adnan     345555555
junaid     50000000
dtype: int64


In [52]:
#(nan) value wo hoti hai jis mein ham koi value na dein q k 0 zero value bhe value hoti hai. 
sdata={"bilal":4500000,"haroon":300000000,"adnan":345555555,"junaid":50000000}
tax_pay=pd.Series(sdata,index=["haroon","bilal","adnan","junaid","ggg"])
print(tax_pay)

haroon    300000000.0
bilal       4500000.0
adnan     345555555.0
junaid     50000000.0
ggg               NaN
dtype: float64


In [53]:
#nan value malom karne k lea
pd.isnull(tax_pay)

haroon    False
bilal     False
adnan     False
junaid    False
ggg        True
dtype: bool

In [54]:
tax_pay.isnull()

haroon    False
bilal     False
adnan     False
junaid    False
ggg        True
dtype: bool

#                                          DATA FRAME

In [55]:
import pandas as pd

In [56]:
s1 = pd.Series([3,2,1,6])
s2 = pd.Series(["a","b","c","d"])
print(s1)
print(s2)

0    3
1    2
2    1
3    6
dtype: int64
0    a
1    b
2    c
3    d
dtype: object


In [57]:
data={"s1":s1,"s2":s2}

In [58]:
frame=pd.DataFrame(data)
print(frame)

   s1 s2
0   3  a
1   2  b
2   1  c
3   6  d


In [59]:
import pandas as pd
s1 = pd.Series([3,2,1,6])
s2 = pd.Series(["a","b","c","d"])
print(s1)
print(s2)
data={"s1":s1,"s2":s2}
frame=pd.DataFrame(data)
print(frame)

0    3
1    2
2    1
3    6
dtype: int64
0    a
1    b
2    c
3    d
dtype: object
   s1 s2
0   3  a
1   2  b
2   1  c
3   6  d


In [60]:
city=["karachi","lahor","islamabad","multan","faislabad"]
years=[2001,2002,2003,2004,2005]
pop=[1.50,2.0,5.2,6.5,4.8]
data1={"city":city,"years":years,"pop":pop}
frame1=pd.DataFrame(data1)
print(frame1)

        city  years  pop
0    karachi   2001  1.5
1      lahor   2002  2.0
2  islamabad   2003  5.2
3     multan   2004  6.5
4  faislabad   2005  4.8


In [61]:
data2={"city":["karachi","lahor","islamabad","multan","faislabad","rawalpindi"],"years":[2001,2002,2003,2004,2005,2006],"pop":[1.50,2.0,5.2,6.5,4.8,3.6]}
frame2=pd.DataFrame(data2,index=["a","s","d","f","g","h"])
print(frame2)

         city  years  pop
a     karachi   2001  1.5
s       lahor   2002  2.0
d   islamabad   2003  5.2
f      multan   2004  6.5
g   faislabad   2005  4.8
h  rawalpindi   2006  3.6


In [62]:
data3={"city":["karachi","lahor","islamabad","multan","faislabad"],"years":[2001,2002,2003,2004,2005,2006],"pop":[2.0,5.2,6.5,4.8,1.6]}
frame3=pd.DataFrame(data2,index=["a","s","d","f","g","h","i"])#index agar value se zada ho ga ya kam ho ga to value error aai ga.
print(frame3)

ValueError: Shape of passed values is (6, 3), indices imply (7, 3)

In [63]:
#agar sari value put na karni ho sirf top 5 print karni ho to(.head()) ki cammend use kare ge
frame2.head()


city  years  pop
a    karachi   2001  1.5
s      lahor   2002  2.0
d  islamabad   2003  5.2
f     multan   2004  6.5
g  faislabad   2005  4.8

In [64]:
# data frame mein columns ki setting change karne k lea
frame2=pd.DataFrame(data2, columns=["city","pop","years"])
frame2.head()

city  pop  years
0    karachi  1.5   2001
1      lahor  2.0   2002
2  islamabad  5.2   2003
3     multan  6.5   2004
4  faislabad  4.8   2005

In [65]:
#columns add karne k lea or sath index dene k lea
frame2=pd.DataFrame(data2, columns=["years","pop","city","dept"],index=["one","two","three","four","five","six"])
frame2


years  pop        city dept
one     2001  1.5     karachi  NaN
two     2002  2.0       lahor  NaN
three   2003  5.2   islamabad  NaN
four    2004  6.5      multan  NaN
five    2005  4.8   faislabad  NaN
six     2006  3.6  rawalpindi  NaN

In [66]:
frame2=pd.DataFrame(data2, columns=["years","pop","city","dept"],index=["one","two","three","four","five","six"])
frame2.head()

years  pop       city dept
one     2001  1.5    karachi  NaN
two     2002  2.0      lahor  NaN
three   2003  5.2  islamabad  NaN
four    2004  6.5     multan  NaN
five    2005  4.8  faislabad  NaN

In [67]:
#columns check karne k lea (.columns)

In [68]:
frame2.columns

Index(['years', 'pop', 'city', 'dept'], dtype='object')

In [69]:
frame2.columns # print likhe bena jupyter sirf last code ko hi print karata hai
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [70]:
print(frame2.columns) 
print(frame2.index)

Index(['years', 'pop', 'city', 'dept'], dtype='object')
Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')


In [71]:
#data frame mein se columns ko call karne k, lea dictinary like notation methord

In [72]:
print(data2)#yy dictinary hai

{'city': ['karachi', 'lahor', 'islamabad', 'multan', 'faislabad', 'rawalpindi'], 'years': [2001, 2002, 2003, 2004, 2005, 2006], 'pop': [1.5, 2.0, 5.2, 6.5, 4.8, 3.6]}


In [73]:
data2["years"]#yy dic mein se call karne k lea

[2001, 2002, 2003, 2004, 2005, 2006]

In [74]:
frame2["city"]#data frame mein se call karne k lea

one         karachi
two           lahor
three     islamabad
four         multan
five      faislabad
six      rawalpindi
Name: city, dtype: object

In [75]:
frame2["pop"]

one      1.5
two      2.0
three    5.2
four     6.5
five     4.8
six      3.6
Name: pop, dtype: float64

In [76]:
#data call attribute style in data frame

In [77]:
frame2.city

one         karachi
two           lahor
three     islamabad
four         multan
five      faislabad
six      rawalpindi
Name: city, dtype: object

In [78]:
frame2.years

one      2001
two      2002
three    2003
four     2004
five     2005
six      2006
Name: years, dtype: int64

In [79]:
frame2.pop

<bound method NDFrame.pop of        years  pop        city dept
one     2001  1.5     karachi  NaN
two     2002  2.0       lahor  NaN
three   2003  5.2   islamabad  NaN
four    2004  6.5      multan  NaN
five    2005  4.8   faislabad  NaN
six     2006  3.6  rawalpindi  NaN>

In [80]:
frame2.dept

one      NaN
two      NaN
three    NaN
four     NaN
five     NaN
six      NaN
Name: dept, dtype: object

In [82]:
frame2.loc["two"]#row ka data malom karne k lea

years     2002
pop          2
city     lahor
dept       NaN
Name: two, dtype: object

In [118]:
frame2.iloc[1,2]

NameError: name 'frame2' is not defined

# Function application And mapping

In [84]:
import numpy as np
import pandas as pd
frame = pd.DataFrame(np.random.randn(4,3)
                             ,columns=list("bde")
                             ,index=["utah","ohio","texas","oregon"])
print(frame)
print(np.abs(frame))#is se frame ki - value + ho jai gi

               b         d         e
utah   -0.521488 -0.234423  1.523107
ohio   -0.425062  0.217040  0.635954
texas   0.459914 -0.404345 -0.054831
oregon  0.792846  0.109271 -0.084763
               b         d         e
utah    0.521488  0.234423  1.523107
ohio    0.425062  0.217040  0.635954
texas   0.459914  0.404345  0.054831
oregon  0.792846  0.109271  0.084763


In [85]:
import numpy as np
import pandas as pd
frame = pd.DataFrame(np.random.randn(4,3)
                             ,columns=list("bde")
                             ,index=["utah","ohio","texas","oregon"])
print(frame)
#print(np.abs(frame))#is ko ab band kar dea
print(frame["d"].min())
print(frame["d"].max())
print(frame["d"].max() - frame["d"].min())

               b         d         e
utah   -0.066832  0.143638 -1.453075
ohio   -0.433245  0.806627  1.484919
texas   1.246301 -0.473517 -0.626413
oregon  0.834603 -1.873878  0.643927
-1.8738776586486963
0.8066267338666664
2.6805043925153624


In [86]:
import numpy as np
import pandas as pd
frame = pd.DataFrame(np.random.randn(4,3)
                             ,columns=list("bde")
                             ,index=["utah","ohio","texas","oregon"])
print(frame)
#print(np.abs(frame))#is ko ab band kar dea
print(frame["d"].min())
print(frame["d"].max())
print(frame["d"].max() - frame["d"].min())

f=lambda x:x.max() - x.min()
df=frame.apply(f)
print(df)

               b         d         e
utah   -0.484187  0.518410 -0.062640
ohio    1.159488 -1.616414 -0.423084
texas  -0.621684 -0.125700 -0.041942
oregon -2.045951  1.619526 -0.215310
-1.6164138349572452
1.6195258164167627
3.235939651374008
b    3.205439
d    3.235940
e    0.381142
dtype: float64


In [87]:
import numpy as np
import pandas as pd
frame = pd.DataFrame(np.random.randn(4,3)
                             ,columns=list("bde")
                             ,index=["utah","ohio","texas","oregon"])
print(frame)
#print(np.abs(frame))#is ko ab band kar dea
print(frame["d"].min())
print(frame["d"].max())
print(frame["d"].max() - frame["d"].min())

f=lambda x:x.max() - x.min()
df=frame.apply(f)
print(df,type(df))#type()   type malom karne k lea hai k kis type ka data hai

               b         d         e
utah    0.426375 -0.505536  1.683763
ohio    0.992082 -1.186877 -1.057721
texas  -0.840293 -0.333308 -0.215113
oregon -0.535176 -0.353805  0.569262
-1.1868769797778422
-0.3333082686329613
0.8535687111448809
b    1.832375
d    0.853569
e    2.741484
dtype: float64 <class 'pandas.core.series.Series'>


In [88]:
import numpy as np
import pandas as pd
frame = pd.DataFrame(np.random.randn(4,3)
                             ,columns=list("bde")
                             ,index=["utah","ohio","texas","oregon"])
print(frame)
#print(np.abs(frame))#is ko ab band kar dea
#print(frame["d"].min())
#print(frame["d"].max())
#print(frame["d"].max() - frame["d"].min())

f=lambda x:x.max() - x.min()
df=frame.apply(f)
print(df)

               b         d         e
utah    0.420991 -0.716906  2.397761
ohio    0.621370  0.544904  0.553950
texas  -1.210316 -0.177960 -0.350352
oregon -0.085371 -0.741193  1.035270
b    1.831686
d    1.286097
e    2.748113
dtype: float64


In [89]:
import numpy as np
import pandas as pd
frame = pd.DataFrame(np.random.randn(4,3)
                             ,columns=list("bde")
                             ,index=["utah","ohio","texas","oregon"])
print(frame)
#print(np.abs(frame))#is ko ab band kar dea
print(frame["d"].min())#minimum num malom karne k lea (d) column se 
print(frame["d"].max())#maximum num malom karne k lea (d) column se
print(frame["d"].max() - frame["d"].min())

f=lambda x:x.max() - x.min()#function banaya hai 
df=frame.apply(f) #columns par apply ho ga k b,d,e colums mein se max mein se min - kar k batai
print(df,type(df))

dc=frame.apply(f, axis=1)#row par apply ho ga k sab row mein se max mein se min - kar k batai
print(dc)

               b         d         e
utah   -0.886111  0.083967  1.906821
ohio    0.609178  0.265943 -0.715656
texas   0.594981 -0.428323  0.437717
oregon -0.480570 -1.294265  0.606311
-1.2942651777006184
0.2659432047113026
1.560208382411921
b    1.495289
d    1.560208
e    2.622477
dtype: float64 <class 'pandas.core.series.Series'>
utah      2.792932
ohio      1.324834
texas     1.023304
oregon    1.900576
dtype: float64


In [90]:
import numpy as np
import pandas as pd
frame = pd.DataFrame(np.random.randn(4,3)
                             ,columns=list("bde")
                             ,index=["utah","ohio","texas","oregon"])
print(frame)
#print(np.abs(frame))#is ko ab band kar dea name k bena hai
print(frame["d"].min())#minimum num malom karne k lea (d) column se 
print(frame["d"].max())#maximum num malom karne k lea (d) column se
print(frame["d"].max() - frame["d"].min())

f=lambda x:x.max() - x.min()#function banaya hai
df=frame.apply(f) #columns par apply ho ga k b,d,e colums mein se max mein se min - kar k batai
print(df,type(df))

dc=frame.apply(f, axis=1)#row par apply ho ga k sab row mein se max mein se min - kar k batai
print(dc)

def min_max(x):#nam k sath function define karna
    minimum=x.min()
    maximum=x.max()
    return pd.Series([minimum , maximum],index=["min","max"])
dd=frame.apply(min_max)
print(dd,type(dd))#type()   type malom karne k lea hai k kis type ka data hai

               b         d         e
utah    1.090367  0.188207  0.107114
ohio    0.088245 -1.360926  0.254805
texas  -0.031488  0.088573  0.300046
oregon  0.717207  0.860561  0.411341
-1.360926173658519
0.860561298076972
2.221487471735491
b    1.121856
d    2.221487
e    0.304228
dtype: float64 <class 'pandas.core.series.Series'>
utah      0.983254
ohio      1.615731
texas     0.331534
oregon    0.449220
dtype: float64
            b         d         e
min -0.031488 -1.360926  0.107114
max  1.090367  0.860561  0.411341 <class 'pandas.core.frame.DataFrame'>


In [83]:
import numpy as np
import pandas as pd
frame = pd.DataFrame(np.random.randn(4,3)
                             ,columns=list("bde")
                             ,index=["utah","ohio","texas","oregon"])
print(frame)
#print(np.abs(frame))#is ko ab band kar dea
print(frame["d"].min())#minimum num malom karne k lea (d) column se 
print(frame["d"].max())#maximum num malom karne k lea (d) column se
print(frame["d"].max() - frame["d"].min())

f=lambda x:x.max() - x.min()#function banaya hai
df=frame.apply(f) #columns par apply ho ga k b,d,e colums mein se max mein se min - kar k batai
print(df,type(df))

dc=frame.apply(f, axis=1)#row par apply ho ga k sab row mein se max mein se min - kar k batai
print(dc)

def min_max(x):#nam k sath function define karna
    #minimum=x.min()# is k bena bhe direct apply kar sakte hain function
    #maximum=x.max()# is k bena bhe direct apply kar sakte hain function
    return pd.Series([x.min(),x.max()],index=["min","max"])#direct apply kea
dd=frame.apply(min_max)#columns wise
print(dd)


dd=frame.apply(min_max, axis=1)#row wise
print(dd)

               b         d         e
utah    2.437257  3.050561 -1.457352
ohio   -0.034556  0.265771 -1.117025
texas  -0.614357 -2.263871  1.068816
oregon -0.885970  0.047087  1.521537
-2.2638714510973874
3.0505614824183467
5.314432933515734
b    3.323227
d    5.314433
e    2.978889
dtype: float64 <class 'pandas.core.series.Series'>
utah      4.507913
ohio      1.382795
texas     3.332688
oregon    2.407507
dtype: float64
            b         d         e
min -0.885970 -2.263871 -1.457352
max  2.437257  3.050561  1.521537
             min       max
utah   -1.457352  3.050561
ohio   -1.117025  0.265771
texas  -2.263871  1.068816
oregon -0.885970  1.521537


In [84]:
#apni practice
def min_max(x):#nam k sath function define karna
    minimum=x.min()
    maximum=x.max()
    return pd.Series([maximum - minimum],index=["max-min"])
dd=frame.apply(min_max)#columns wise
print(dd)


dd=frame.apply(min_max, axis=1)#row wise
print(dd)

                b         d         e
max-min  3.323227  5.314433  2.978889
         max-min
utah    4.507913
ohio    1.382795
texas   3.332688
oregon  2.407507


In [85]:
#apni practice
def min_max(x):#nam k sath function define karna
    #minimum=x.min()
    #maximum=x.max()
    return pd.Series([x.max() - x.min()],index=["max-min"])#direct apply function
dd=frame.apply(min_max)#columns wise
print(dd)


dd=frame.apply(min_max, axis=1)#row wise
print(dd)

                b         d         e
max-min  3.323227  5.314433  2.978889
         max-min
utah    4.507913
ohio    1.382795
texas   3.332688
oregon  2.407507


# sorting and ranking

In [87]:
x=np.arange(8)

In [88]:
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [91]:
x.reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [101]:
x.reshape((2,4))# .reshape() reshape ka formula hai

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [135]:
#sort by ranking

In [136]:
import numpy as np
import pandas as pd
frame1=pd.DataFrame(np.arange(8).reshape((2,4)),index=["three","one"],columns=["d","a","c","b"])
print(frame1)
print(frame1.sort_index(axis=1))#sort_indexing karne se column name tarteeb se aa jate hain agr axis k sath dea jai to
print(frame1.sort_index(axis=1,ascending=False))#asscending False dene se end se tarteeb di jati hai
print(frame1.sort_index())#defult mein row ki indexing tarteeb di jati hai or true hoti hai 
print(frame1.sort_index(axis=0,ascending=False))
                    

       d  a  c  b
three  0  1  2  3
one    4  5  6  7
       a  b  c  d
three  1  3  2  0
one    5  7  6  4
       d  c  b  a
three  0  2  3  1
one    4  6  7  5
       d  a  c  b
one    4  5  6  7
three  0  1  2  3
       d  a  c  b
three  0  1  2  3
one    4  5  6  7


In [137]:
#sort by value

In [146]:
print(frame1.sort_values(by="b"))
print(frame1.rank(ascending=False,method="max"))
print(frame1.rank(ascending=True,method="max"))
print(frame1.rank(ascending=False,method="min"))
print(frame1.rank(ascending=True,method="min"))
print(frame1.rank(axis="columns"))

       d  a  c  b
three  0  1  2  3
one    4  5  6  7
         d    a    c    b
three  2.0  2.0  2.0  2.0
one    1.0  1.0  1.0  1.0
         d    a    c    b
three  1.0  1.0  1.0  1.0
one    2.0  2.0  2.0  2.0
         d    a    c    b
three  2.0  2.0  2.0  2.0
one    1.0  1.0  1.0  1.0
         d    a    c    b
three  1.0  1.0  1.0  1.0
one    2.0  2.0  2.0  2.0
         d    a    c    b
three  1.0  2.0  3.0  4.0
one    1.0  2.0  3.0  4.0


In [148]:
print(frame.sort_values(by="b"))
print(frame.rank(ascending=False,method="max"))
print(frame.rank(ascending=True,method="max"))
print(frame.rank(ascending=False,method="min"))
print(frame.rank(ascending=True,method="min"))
print(frame.rank(axis="columns"))

               b         d         e
oregon -0.885970  0.047087  1.521537
texas  -0.614357 -2.263871  1.068816
ohio   -0.034556  0.265771 -1.117025
utah    2.437257  3.050561 -1.457352
          b    d    e
utah    1.0  1.0  4.0
ohio    2.0  2.0  3.0
texas   3.0  4.0  2.0
oregon  4.0  3.0  1.0
          b    d    e
utah    4.0  4.0  1.0
ohio    3.0  3.0  2.0
texas   2.0  1.0  3.0
oregon  1.0  2.0  4.0
          b    d    e
utah    1.0  1.0  4.0
ohio    2.0  2.0  3.0
texas   3.0  4.0  2.0
oregon  4.0  3.0  1.0
          b    d    e
utah    4.0  4.0  1.0
ohio    3.0  3.0  2.0
texas   2.0  1.0  3.0
oregon  1.0  2.0  4.0
          b    d    e
utah    2.0  3.0  1.0
ohio    2.0  3.0  1.0
texas   2.0  1.0  3.0
oregon  1.0  2.0  3.0


In [149]:
print(frame.rank(axis="columns"))

          b    d    e
utah    2.0  3.0  1.0
ohio    2.0  3.0  1.0
texas   2.0  1.0  3.0
oregon  1.0  2.0  3.0


# summarizing and computing descriptive statistics

In [156]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]]
                ,index=["a","b","c","d"],columns=["one","two"])#yy ak data frame banaya hai
print(df)
print(df.sum())
print(df.sum(axis="columns"))#axis=1 or axis="columns" same kam karte hain
print(df.sum(axis=1))#axis=1 or axis="columns" same kam karte hain

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3
one    9.25
two   -5.80
dtype: float64
a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64
a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64


In [157]:
#mean opration

In [159]:
print(df)
x=df.mean()
print(x)

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3
one    3.083333
two   -2.900000
dtype: float64


In [164]:
print(df)
x=df.mean()
print(x)
x=df.mean(axis="columns",skipna=False)#mean ki ok value malom karne k lea istemal hota hai
print(x)
x=df.mean(axis="columns",skipna=True)
print(x)

    one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3
one    3.083333
two   -2.900000
dtype: float64
a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64
a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64


# unique value

In [184]:
df1=pd.DataFrame([[1.4,1.4,1.5,np.nan],[7.1,-4.5,1.5,1.4],[1.4,np.nan,0.5,np.nan]
                ,[0.75,-1.3,1.3,np.nan]],index=["a","b","c","d"],columns=["one","two","three","four"])
print(df1)
print()
print(df1["one"].unique(),df1["two"].unique() )#jo value 2 ya us se zada ho gi usa ak hi dafa print karai ga
print(df1["one"].value_counts())


    one  two  three  four
a  1.40  1.4    1.5   NaN
b  7.10 -4.5    1.5   1.4
c  1.40  NaN    0.5   NaN
d  0.75 -1.3    1.3   NaN

[1.4  7.1  0.75] [ 1.4 -4.5  nan -1.3]
1.40    2
0.75    1
7.10    1
Name: one, dtype: int64


# arithmatic Methods with fill value

In [101]:
df2=pd.DataFrame(np.arange(12).reshape(3,4),columns=list("abcd"))
df3=pd.DataFrame(np.arange(20).reshape((4,5)),columns=list("abcde"))
print(df2)
print(df3)
df3.loc[1,"b"]=np.nan#.loc[ ] yy notation use ho ga.
print(df3)
df4=df2+df3

print("direct operation without value")
print(df4)
print(".....................")
#we can use add method for filling NaN cell with a value
#NaN WILL BE peplaced by 0 and than addition operation will apply
print ("addition using a method with replacing NaN with 0")
df4=df2.add(df3,fill_value=0)
print(df4)

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
    a     b   c   d   e
0   0   1.0   2   3   4
1   5   NaN   7   8   9
2  10  11.0  12  13  14
3  15  16.0  17  18  19
direct operation without value
      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN
.....................
addition using a method with replacing NaN with 0
      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [102]:
#DataFrame - Series

In [107]:
import numpy as np
import pandas as pd
frame2 = pd.DataFrame(np.random.randn(4,3)
                             ,columns=list("bde")
                             ,index=["utah","ohio","texas","oregon"])
print(frame2)


series=pd.Series([1,2,3],index=list("bde"))
print(series.index,series.values)

print(frame2 - series)


               b         d         e
utah    0.860269  1.085983 -0.458238
ohio    0.518218  0.764106 -0.510473
texas   0.193018  0.314776 -0.153384
oregon  0.336624 -0.450685  0.150669
Index(['b', 'd', 'e'], dtype='object') [1 2 3]
               b         d         e
utah   -0.139731 -0.914017 -3.458238
ohio   -0.481782 -1.235894 -3.510473
texas  -0.806982 -1.685224 -3.153384
oregon -0.663376 -2.450685 -2.849331


# arithmetic and data alignment.

In [94]:
import numpy as np
import pandas as pd
data_df=pd.DataFrame(np.arange(16).reshape(4,4),index=["ohio","colorado","utah","newyork"],
                     columns=["one","two","three","four"])
print(data_df)
print(data_df.loc["colorado",["two","three"]])#.loc[] row or columns ka name likh kar call kare ge jo dekhni ho
print(data_df.iloc[2,[3,0,1]])#.iloc[] row or columns kawo num batai ge jis num ka data dekhna hai
print(data_df.iloc[:])#.loc[:] sara data print ho jai ga
print(data_df.iloc[:2,:3])#kitni row or kitne columns dekhne hain
print(data_df.iloc[:,:3])#row sab or jitne columns dekhne ho wo batai ge.
print()
#atribute style hai yy
print(data_df.one[2:])#columns one ki 2 value print ki hon gi
print()
#dictionary style
print(data_df[["one","two"]][:2])

          one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
newyork    12   13     14    15
two      5
three    6
Name: colorado, dtype: int32
four    11
one      8
two      9
Name: utah, dtype: int32
          one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
newyork    12   13     14    15
          one  two  three
ohio        0    1      2
colorado    4    5      6
          one  two  three
ohio        0    1      2
colorado    4    5      6
utah        8    9     10
newyork    12   13     14

utah        8
newyork    12
Name: one, dtype: int32

          one  two
ohio        0    1
colorado    4    5


In [17]:
data_df1=pd.DataFrame(np.arange(16).reshape(4,4),index=["ohio","colorado","utah","newyork"],
                     columns=["one","two","three","four"])
data_df2=pd.DataFrame(np.arange(16).reshape(4,4),index=["bilal","colorado","utah","newyork"],
                     columns=["one","three","four","six"])
print(data_df1)
print(data_df2)
data_df3=data_df1 + data_df2
print(data_df3)

          one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
newyork    12   13     14    15
          one  three  four  six
bilal       0      1     2    3
colorado    4      5     6    7
utah        8      9    10   11
newyork    12     13    14   15
          four   one  six  three  two
bilal      NaN   NaN  NaN    NaN  NaN
colorado  13.0   8.0  NaN   11.0  NaN
newyork   29.0  24.0  NaN   27.0  NaN
ohio       NaN   NaN  NaN    NaN  NaN
utah      21.0  16.0  NaN   19.0  NaN


In [21]:
data_df3=data_df1.add(data_df2,fill_value=0)
print(data_df3)

          four   one   six  three   two
bilal      2.0   0.0   3.0    1.0   NaN
colorado  13.0   8.0   7.0   11.0   5.0
newyork   29.0  24.0  15.0   27.0  13.0
ohio       3.0   0.0   NaN    2.0   1.0
utah      21.0  16.0  11.0   19.0   9.0


In [85]:
#data calling numpy and dictionary style

In [31]:
print(data_df,"\n")
print(data_df[["one","three"]])#num one or three columns ko call ki
print(data_df[2:])#num 2 se neche jitni row hain un sab ko call ki
print(data_df[1:3])#num 1 se num 3 tak ki row call ki

          one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
newyork    12   13     14    15 

          one  three
ohio        0      2
colorado    4      6
utah        8     10
newyork    12     14
         one  two  three  four
utah       8    9     10    11
newyork   12   13     14    15
          one  two  three  four
colorado    4    5      6     7
utah        8    9     10    11


In [95]:
#data calling condition base

In [103]:
print(data_df[data_df>5])# condition 5 se bhara data print ni ho ga us ki jaga nan aai ga
print()
print(data_df[data_df["three"]>5])#condition "three" column mein 5 se zada value wali sab row print hogi
print()
print(data_df.three[data_df["three"]>5])#condition jo column print karana ho

           one   two  three  four
ohio       NaN   NaN    NaN   NaN
colorado   NaN   NaN    6.0   7.0
utah       8.0   9.0   10.0  11.0
newyork   12.0  13.0   14.0  15.0

          one  two  three  four
colorado    4    5      6     7
utah        8    9     10    11
newyork    12   13     14    15

colorado     6
utah        10
newyork     14
Name: three, dtype: int32


In [107]:
#condition boolean dataframe jahan wo condition value ho gi wahan true or jahan ni ho gi wahan false aai ga
print(data_df>5)#sare data par condition lagana
print(data_df["three"]>5)#kisi makhsoos data par condition lagana jase "three" num columns par lagai
vv=data_df["three"]>5
print(data_df[vv])
print(data_df[data_df["three"]>5])


            one    two  three   four
ohio      False  False  False  False
colorado  False  False   True   True
utah       True   True   True   True
newyork    True   True   True   True
ohio        False
colorado     True
utah         True
newyork      True
Name: three, dtype: bool
          one  two  three  four
colorado    4    5      6     7
utah        8    9     10    11
newyork    12   13     14    15
          one  two  three  four
colorado    4    5      6     7
utah        8    9     10    11
newyork    12   13     14    15


In [32]:
#deleting data for .drop

In [46]:
print(data_df1)
print(data_df1.drop("two",axis=1))#columns delet karne k lea
print(data_df1.drop("ohio",axis=0))#row delet karne k lea
         #yy sirf yahi delet ho ga main data se ni
print(data_df1)

          one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
newyork    12   13     14    15
          one  three  four
ohio        0      2     3
colorado    4      6     7
utah        8     10    11
newyork    12     14    15
          one  two  three  four
colorado    4    5      6     7
utah        8    9     10    11
newyork    12   13     14    15
          one  two  three  four
ohio        0    1      2     3
colorado    4    5      6     7
utah        8    9     10    11
newyork    12   13     14    15


In [47]:
#reindex with ffill methods

In [84]:
bilal=pd.DataFrame(["orange","yellow","blue"],index=[0,3,6])
print(bilal)
bilal1=bilal.reindex(range(9))
print(bilal1)
bilal1=bilal.reindex(range(9),method="ffill")
print(bilal1)
bilal2=bilal1.reindex(range(2,11))
print(bilal2)

        0
0  orange
3  yellow
6    blue
        0
0  orange
1     NaN
2     NaN
3  yellow
4     NaN
5     NaN
6    blue
7     NaN
8     NaN
        0
0  orange
1  orange
2  orange
3  yellow
4  yellow
5  yellow
6    blue
7    blue
8    blue
         0
2   orange
3   yellow
4   yellow
5   yellow
6     blue
7     blue
8     blue
9      NaN
10     NaN


In [57]:
#reindex columns name

In [59]:
print(data_df2)

          one  three  four  six
bilal       0      1     2    3
colorado    4      5     6    7
utah        8      9    10   11
newyork    12     13    14   15


In [71]:
c1=["one","good","men","six","no"]
c2=data_df2.reindex(columns=c1)
print(c2)
c2=data_df2.reindex(columns=(c1),method="ffill")#columns par ffill ka methods use ni ho raha hai
print(c2)

          one  good  men  six  no
bilal       0   NaN  NaN    3 NaN
colorado    4   NaN  NaN    7 NaN
utah        8   NaN  NaN   11 NaN
newyork    12   NaN  NaN   15 NaN


ValueError: index must be monotonic increasing or decreasing